name: Python Package using Conda

on: [push]


jobs:
  build-linux:
    runs-on: ubuntu-latest
#    container: goughmj/jupyter_ci_container:latest
#    defaults:
#      run:
#        shell: bash -l {0}
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.2
      uses: actions/setup-python@v2 ## needed for caching
      with:
        python-version: 3.10.2
        cache: 'pip'
    - name: Install dependencies
      run: |
        pip install pytest
        pip install nbval
        pip install -r CIenvironment.yml
    - name: Test notebooks with pytest nbval
      run: |
        pytest --nbval
