name: MatrixTest
on: [push, pull_request]
jobs:
  list-notebooks:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(find notebooks -name "*.ipynb" | jq -cnR '[inputs | select(length>0)]')"
  check:
    needs: list-notebooks
    runs-on: ubuntu-latest
    strategy:
        matrix:
            notebooks: ${{ fromJson(needs.list-notebooks.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2   
      #- run: | 
      #      pip install -r ${${{ matrix.notebooks }}%/*}/requirements.txt
      - uses: actions/checkout@v2
      - name: Set up Python 3.8.12
        uses: actions/setup-python@v2 ## needed for caching
        with:
          python-version: 3.8.12
          cache: 'pip'
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          #conda env update --file CIenvironment.yml --name base
          pip install -r CIenvironment.yml
          pip install pytest
          pip install nbval
          pip install nbconvert
      - name: Execute notebooks
        run: |
          jupyter nbconvert --template classic --to html --execute ${{ matrix.notebooks }}

