name: MatrixTest
on: [push, pull_request]
jobs:
  list-notebooks:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(find notebooks -name "*.ipynb" | jq -cnR '[inputs | select(length>0)]')"
  check:
    needs: list-notebooks
    runs-on: ubuntu-latest
    strategy:
        matrix:
            manifest: ${{ fromJson(needs.list-notebooks.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2   
      - run: | 
            echo ${{ martix.notebooks }}
        
